version: '3.8'
services:
  kcdb:
    image: postgres
    volumes:
      - kcdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: keycloak/keycloak
    volumes:
      - ./keycloak_import:/opt/keycloak/data/import
    command:
      - "start-dev"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: kcdb
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8180
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8180
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm_export.json
    depends_on:
      - kcdb
    ports:
      - "8180:8180"

volumes:
  kcdb_data: